//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Xamarin.Forms custom CollectionView with drag and drop and more (former named Hor" +
    "izontalListView), including horizontal list view, carousel, vertical and grid la" +
    "yout.")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Sharpnado.CollectionView")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2021")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0")]
[assembly: System.Reflection.AssemblyVersion("2.0.0")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.CollectionView")]


