//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.8.2")]
[assembly: System.Reflection.AssemblyFileVersion("1.8.2")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Sharpnado.HorizontalListView")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2020")]
[assembly: System.Reflection.AssemblyDescription("Xamarin Forms HorizontalListView, including carousel, vertical and grid layout.")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.HorizontalListView")]


