//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Xamarin Forms HorizontalListView, including carousel, vertical and grid layout.")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Sharpnado.HorizontalListView")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2020")]
[assembly: System.Reflection.AssemblyFileVersion("1.8.2")]
[assembly: System.Reflection.AssemblyVersion("1.8.2")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.HorizontalListView")]


